import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy — RentOut",
  description: "How RentOut collects, uses, and protects your personal data.",
};

const S = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <section style={{ marginBottom: 36 }}>
    <h2 style={{ fontSize: 19, fontWeight: 800, letterSpacing: "-0.02em", color: "#f0f0fa", marginBottom: 12 }}>{title}</h2>
    <div style={{ fontSize: 14.5, color: "#a8a8c8", lineHeight: 1.8 }}>{children}</div>
  </section>
);

export default function PrivacyPage() {
  return (
    <div style={{ background: "var(--bg)", minHeight: "100vh" }}>
      <nav style={{ position: "sticky", top: 0, zIndex: 99, background: "rgba(7,7,10,0.85)", borderBottom: "1px solid rgba(255,255,255,0.04)", padding: "0 28px", height: 58, display: "flex", alignItems: "center", backdropFilter: "blur(16px)" }}>
        <Link href="/" style={{ fontSize: 14, fontWeight: 700, color: "#8888aa", textDecoration: "none" }}>← RentOut</Link>
      </nav>
      <main style={{ maxWidth: 720, margin: "0 auto", padding: "72px 24px 96px" }}>
        <p style={{ fontSize: 12, fontWeight: 700, letterSpacing: "0.16em", color: "var(--accent)", textTransform: "uppercase", marginBottom: 14 }}>Legal</p>
        <h1 style={{ fontSize: "clamp(30px, 5vw, 44px)", fontWeight: 900, letterSpacing: "-0.04em", color: "#f8f8fa", marginBottom: 10 }}>Privacy Policy</h1>
        <p style={{ fontSize: 13.5, color: "#666688", marginBottom: 48 }}>Last updated: July 5, 2026</p>

        <S title="The short version">
          <p>We collect the minimum we need to run the RentOut early-access waitlist: your name, email address, and city. We use it only to manage your waitlist position and to contact you about the launch. We never sell your data. You can ask us to delete it at any time.</p>
        </S>

        <S title="1. What we collect">
          <p style={{ marginBottom: 10 }}>When you join the waitlist at getrentout.me we collect:</p>
          <ul style={{ paddingLeft: 20, display: "flex", flexDirection: "column", gap: 8 }}>
            <li><strong style={{ color: "#d0d0e8" }}>Name, email address, and city</strong> — the details you type into the signup form.</li>
            <li><strong style={{ color: "#d0d0e8" }}>Referral data</strong> — if you arrived through someone&apos;s referral link, we record that connection so both of you get referral credit.</li>
            <li><strong style={{ color: "#d0d0e8" }}>Basic technical data</strong> — standard server logs (such as IP address and browser type) generated by our hosting provider for security and reliability.</li>
          </ul>
        </S>

        <S title="2. How we use it">
          <ul style={{ paddingLeft: 20, display: "flex", flexDirection: "column", gap: 8 }}>
            <li>To hold and manage your waitlist position and referral standing.</li>
            <li>To email you about your signup, your position, and the launch of RentOut in your region.</li>
            <li>To prevent abuse, duplicate signups, and fraud on the waitlist.</li>
          </ul>
          <p style={{ marginTop: 10 }}>We do not sell, rent, or trade your personal data to anyone. We do not send third-party marketing.</p>
        </S>

        <S title="3. Who processes your data">
          <p>Your data is stored and processed by reputable infrastructure providers acting on our behalf: our hosting platform (Vercel), our database provider (Supabase), and our email delivery provider (Resend). Each processes your data only to provide their service to us.</p>
        </S>

        <S title="4. How long we keep it">
          <p>We keep your waitlist data until RentOut launches in your region and your account is created, or until you ask us to remove you — whichever comes first. If you ask to be removed, we delete your record from the waitlist database.</p>
        </S>

        <S title="5. Your rights">
          <p>You can ask us at any time to: see the data we hold about you, correct it, or delete it entirely. Email <a href="mailto:support@getrentout.me" style={{ color: "var(--accent)" }}>support@getrentout.me</a> from the address you signed up with and we&apos;ll take care of it promptly. Depending on where you live (for example the EU/EEA under GDPR), you may have additional statutory rights, and we honor them.</p>
        </S>

        <S title="6. Children">
          <p>RentOut is not directed at children. You must be at least 18 years old (or the age of majority in your jurisdiction) to join the waitlist and to earn on RentOut.</p>
        </S>

        <S title="7. Changes to this policy">
          <p>If we change this policy in a meaningful way, we will update the date at the top and, for significant changes, notify you by email.</p>
        </S>

        <S title="8. Contact">
          <p>Privacy questions or requests: <a href="mailto:support@getrentout.me" style={{ color: "var(--accent)" }}>support@getrentout.me</a> · General: <a href="mailto:hello@getrentout.me" style={{ color: "var(--accent)" }}>hello@getrentout.me</a></p>
        </S>

        <div style={{ borderTop: "1px solid var(--border)", paddingTop: 24, marginTop: 12, display: "flex", gap: 20 }}>
          <Link href="/terms" style={{ fontSize: 13.5, color: "#8888aa", textDecoration: "none" }}>Terms of Service →</Link>
          <Link href="/" style={{ fontSize: 13.5, color: "#8888aa", textDecoration: "none" }}>Back to home</Link>
        </div>
      </main>
    </div>
  );
}
